# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push Docker image with Maven
      run: |
        chmod +x mvnw
        ./mvnw spring-boot:build-image -Dmaven.test.skip=true -Dspring-boot.build-image.imageName=m208/sysu-pan-server
        echo ${{ secrets.CR_TOKEN }} | docker login ghcr.io -u robinWongM --password-stdin
        docker tag docker.io/m208/sysu-pan-server:latest ghcr.io/robinwongm/sysu-pan-server:latest
        docker push ghcr.io/robinwongm/sysu-pan-server:latest
        docker tag docker.io/m208/sysu-pan-server:latest public.ecr.aws/s5q8x3r4/sysu-pan-server:latest
        docker push public.ecr.aws/s5q8x3r4/sysu-pan-server
